#
# Manages the version protocol for servers; Please keep in mind that the author of ViaFabric is NOT responsible for unexpected punishments,
# If you happen to get banned with this then we can't do anything about it!
#
client-side-version: -2
enable-client-side: true
hide-button: false
ignore-registry-sync-errors: true
#
# Since these servers have either very strict anti-cheats or include their own protocol-compatibility system,
# They will be blacklisted so that the user cannot try to tamper with ViaFabric just to join servers that way.
#
client-side-force-disable:
- cytooxien.de
- '*.cytooxien.de'
- gommehd.net
- '*.gommehd.net'
- hoplite.gg
- '*.hoplite.gg'
- hypixel.net
- '*.hypixel.net'
- mccisland.net
- '*.mccisland.net'
- minemen.club
- '*.minemen.club'
- pvplegacy.net
- '*.pvplegacy.net'
- wynncraft.com
- '*.wynncraft.com'
