#
# Manages the version protocol for servers; Please keep in mind that the author of ViaFabric is NOT responsible for unexpected punishments,
# If you happen to get banned with this then we can't do anything about it!
#
client-side-version: -2
enable-client-side: true
hide-button: false
#
# Since these servers have either very strict anti-cheats or include their own protocol-compatibility system,
# They will be blacklisted so that the user cannot try to tamper with ViaFabric just to join servers that way.
#
client-side-force-disable:
- antiac.net
- '*.antiac.net'
- autcraft.com
- '*.autcraft.com'
- bedwarspractice.club
- '*.bedwarspractice.club'
- brawl.com
- '*.brawl.com'
- bridger.land
- '*.bridger.land'
- cubecraft.net
- '*.cubecraft.net'
- gommehd.net
- '*.gommehd.net'
- havocmc.net
- '*.havocmc.net'
- hypixel.net
- '*.hypixel.net'
- imaginefun.net
- '*.imaginefun.net'
- lotc.co
- '*.lotc.co'
- lunar.gg
- '*.lunar.gg'
- mccisland.net
- '*.mccisland.net'
- mcbrawl.com
- '*.mcbrawl.com'
- mcmiddleearth.com
- '*.mcmiddleearth.com'
- mcplayhd.net
- '*.mcplayhd.net'
- minehut.com
- '*.minehut.com'
- minehut.gg
- '*.minehut.gg'
- minemen.club
- '*.minemen.club'
- mineplex.com
- '*.mineplex.com'
- minescape.me
- '*.minescape.me'
- performium.net
- '*.performium.net'
- piratemc.com
- '*.piratemc.com'
- potion.land
- '*.potion.land'
- potterworldmc.com
- '*.potterworldmc.com'
- pvplegacy.net
- '*.pvplegacy.net'
- pvp.land
- '*.pvp.land'
- wynncraft.com
- '*.wynncraft.com'
