#
# Update configuration goes here.
#

checkforupdates: false

#
# Supported version ping configuration goes here.
#

send-supported-versions: true

#
# Versions we should not support for this client, there are multiple reasons why we do this:
#
# 1. The specific versions constantly create connection errors and fail to establish a proper connection.
# 2. There are multiple bugs left-and-right that these versions have which causes inconsistent performance, issues with gameplay, etc.
# 3. Support for these have been longly dropped similar to hypixel's approach back in febuary 2nd 2022; hence this was followed along.
#

block-protocols: []
block-versions:
- 1.7-1.7.5
- 1.7.6-1.7.10
- '1.9'
- 1.9.1
- 1.9.2
- 1.9.3/4
- 1.10.x
- '1.11'
- 1.11.1/2
- '1.13'
- 1.13.1
- 1.13.2

#
# Messages that should be displayed to the player when disconnected by Via* itself,
# This includes a switch if we want to debug conversions or not.
#

block-disconnect-msg: §cThis version cannot be used for this server as it is not supported.
reload-disconnect-msg: §6This server has been reloaded, Please connect back to the server again.
suppress-conversion-warnings: true

#
# Watchdog-Related configuration goes here,
#
# Since this is known for being annoying with a burning passion, the delay is increased by a long-shot unless
# the server is in a cold state then feel free to modify this yourself.
#

max-pps: -1
max-pps-kick-msg: §cSomething went wrong with your connection!
tracking-max-warnings: 175000
tracking-max-kick-msg: §cSomething went wrong with your connection!
tracking-period: -1
tracking-warning-pps: 175000

#
# ViaFabric patches for 1.9.x go here,
#
# This contains a list of patches that are used to try and workaround problems that previous 1.9.x clients have been getting without them,
# While this will not end up in a perfect shape, this will make an attempt on improving critical problems with specific clients.
#

1_13-tab-complete-delay: 3
cache-1_17-light: true
chat-nbt-fix: true
chat-types-1_19:
  "chat.type.text": "<%s> %s"
  "chat.type.announcement": "[%s] %s"
  "commands.message.display.incoming": "%s whispers to you: %s"
  "chat.type.team.text": "%s <%s> %s"
  "chat.type.emote": "* %s %s"
disable-1_13-auto-complete: true
fix-1_14-health-nan: true
fix-infested-block-breaking: true
fix-low-snow-collision: true
fix-non-full-blocklight: true
flowerstem-when-block-above: false
forced-use-1_17-resource-pack: true
hologram-patch: true
hologram-y: -0.96
ignore-long-1_16-channel-names: true
piston-animation-patch: true
reduce-blockstorage-memory: false
resource-pack-1_17-prompt: §9This server requires the resource pack to be enabled in order to display other contents properly.
serverside-blockconnections: true
team-colour-fix: true
truncate-1_14-books: true
use-1_15-instant-respawn: false
vine-climb-fix: true

#
# ViaFabric patch (1.8+) configuration goes here,
#
# This is a similarity to the 1.9.x patches but related to just 1.8.x and prior instead,
# But we will use these patches along in case anything else is missing.
#

auto-team: false
bossbar-anti-flicker: false
bossbar-patch: true
chunk-border-fix: true
force-json-transform: true
item-cache: true
left-handed-handling: true
minimize-cooldown: true
no-delay-shield-blocking: false
prevent-collision: false
replace-pistons: false
replacement-piston-id: 0
shield-blocking: true
show-shield-when-sword-in-hand: true
simulate-pt: true
suppress-metadata-errors: true
use-new-deathmessages: true
use-new-effect-indicator: true

#
# World-Name translator configuration goes here,
#
# This is where we can specify the source's origin name and have it translated as the one we want,
# This may conflict with other world names that use similar friendly names but usually shouldn't happen on purpose.
#

map-1_16-world-names:
  atlantis: atlantis:atlantis
  blended_world: world_blender:world_blender
  bright_overworld: daylightdimension:daylight_dimension
  bsr: bsr:bsr
  bsr_orbit: bsr:overworld_orbit
  bumblezone: the_bumblezone:the_bumblezone
  candy_world: betterswords:candy_dimension
  cave_world: mining_dims:caving_dim
  crystal_world: palpexs_live:crystaldimsnion
  dark_caverns: dark_caverns:dark_caverns
  dark_dungeon: dimdoors:dungeon_pockets
  dark_nether: better_nether_update:darkdimension
  dark_ocean: agape:europa_ocean
  eggcellent: the_eggcellent_mod:eggcellent_dimension
  ele_land: eleworld:eleland
  emprus: the_emprus_max:emprus
  end: minecraft:the_end
  europa: agape:europa_surface
  flying_death: palpexs_live:flyingdeath
  fraiya: lint:fraiya
  ganymede: agape:ganymede
  glar_lands: glarlands:glarlands
  heaven: heaven:heaven
  herobrines_home: utopiacraft:herobrine_dimension
  hunting_world: mining_dims:hunting_dim
  io: agape:io
  lane: revsdimensionmod:lane_dimension
  limbo: dimdoors:limbo
  magnificent_lands: realmofmagnis:magnificent_lands
  meatopia: pork:meatopia
  mechanical: mechanical_mobs:god_dimension
  mechanical_forest: mechanical_mobs:mechanical_forest
  mechanical_slimes: mechanical_mobs:slime_dimension
  mechanical_world: mechanical_mobs:mechanical_world
  mercury: agape:mercury
  mining_end: mining_dimention:endminingdimension
  mining_horizon: minershorizon:miners_horizon
  mining_nether_world: mining_dims:nethering_dim
  mining_world: mining_dims:mining_dim
  molsh: mushroommill:molsh
  moon: agape:moon_surface
  mushy: mushroommill:mushy
  mutt: mushroommill:mutt
  mystic: oretacular:mystic_dimension
  nectere: hotm:nectere
  nether: minecraft:the_nether
  niccdsf: aywen_binggings_:niccdsf
  orbit: agape:overworld_orbit
  ore_land: eleworld:oreland
  overgrown: overgrowncities:overgrowth
  overworld: minecraft:overworld
  paridise_islands: moron_mobs:paridise_islands
  popcorn_world: betterswords:popcorn_dimension
  purple_land: purple_land:purple_dimension
  prehistoric: eymbra:prehistoric
  radioactive: lukerosmod:radioactive_dimension
  red_planet: agape:red_planet
  scale_vacuum: scalevacuum:scale_vacuum
  simple_void: simplevoidworld:simplevoidworld
  sky_lands: revsdimensionmod:sky_lands_dimenson
  space: astromine:earth_space
  spiderian: oretactular:spiderian_dimension
  starship: agape:starship_1
  sweet_and_savory: betterswords:sweet_and_savory_dimension
  the_abyss: moron_mobs:abyss
  the_forest: liminals:the_forest
  the_hallow: thehallow:spooky
  the_mines: liminals:the_mines
  the_laboratory: createlab:laboratory
  the_parallax: nitramod:the_parallax
  the_private_room: dimdoors:personal_pockets
  the_public_room: dimdoors:public_pockets
  titan: agape:titan
  under_void: divine_faith:undervoid
  utopia: utopiacraft:utopiadimension
