#
# ViaVersion configuration goes here,
#
# This allows the entire compatibility system to be re-configured in most cases when
# viaversion is involved in older servers and require translation towards newer clients,
# but can also work out with certain older clients where other modes are absolutely necessary.
#
# References to every config detail can be discovered here:
# https://github.com/ViaVersion/ViaVersion/blob/master/common/src/main/resources/assets/viaversion/config.yml
#
# (Not everything listed in the default config itself are included as ViaFabric automatically cuts them for various reasons)
#
#
# Update configuration goes here.
#
checkforupdates: false
#
# Supported version ping configuration goes here.
#
send-supported-versions: true
#
# Versions we should not support for this client, there are multiple reasons why we do this:
#
# 1. The specific versions constantly create connection errors and fail to establish a proper connection.
# 2. There are multiple bugs left-and-right that these versions have which causes inconsistent performance, issues with gameplay, etc.
# 3. Support for these have been longly dropped similar to hypixel's approach back in febuary 2nd 2022; hence this was followed along.
#
block-protocols: []
block-versions:
- 1.4.6/7
- 1.5/1.5.1
- 1.5.2
- 1.6.1
- 1.6.2
- 1.6.3
- 1.6.4
- 1.7.2-1.7.5
- 1.7.6-1.7.10
- '1.9'
- 1.9.1
- 1.9.2
- 1.9.3/4
- 1.10.x
- '1.11'
- 1.11.1/2
- '1.13'
- 1.13.1
- 1.13.2
#
# Messages that should be displayed to the player when disconnected by Via* itself,
# This includes a switch if we want to debug conversions or not.
#
block-disconnect-msg: §cThis version cannot be used for this server as it is not supported.
reload-disconnect-msg: §6This server has been reloaded, Please connect back to the server again.
suppress-conversion-warnings: true
#
# Packet limitation configuration goes here,
#
# This manages the packet limitation system in order to kick people with go over the threshold,
# However because this was later merged into Paper 1.17.1 and newer, this is considered pointless to have.
#
max-pps: -1
max-pps-kick-msg: §cSomething went wrong with your connection!
tracking-max-warnings: 18000
tracking-max-kick-msg: §cSomething went wrong with your connection!
tracking-period: -1
tracking-warning-pps: 18000
#
# ViaFabric patches for 1.9.x - 1.19.x go here,
#
# This contains a list of patches that are used to try and workaround problems that previous 1.9.x clients have been getting without them,
# While this will not end up in a perfect shape, this will make an attempt on improving critical problems with specific clients.
#
1_13-tab-complete-delay: 3
armor-toggle-fix: true
cache-1_17-light: true
chat-nbt-fix: true
disable-1_13-auto-complete: true
fix-1_14-health-nan: true
fix-infested-block-breaking: true
fix-low-snow-collision: true
fix-non-full-blocklight: true
flowerstem-when-block-above: false
forced-use-1_17-resource-pack: true
hologram-patch: true
hologram-y: -0.96
ignore-long-1_16-channel-names: true
piston-animation-patch: true
reduce-blockstorage-memory: false
register-userconnections-on-join: true
resource-pack-1_17-prompt: §9This server requires the resource pack to be enabled in order to display other contents properly.
serverside-blockconnections: true
team-colour-fix: true
truncate-1_14-books: true
use-1_15-instant-respawn: false
vine-climb-fix: true
#
# ViaFabric patch (1.8+) configuration goes here,
#
# This is a similarity to the 1.9.x - 1.19.x patches but related to just 1.8.x and prior instead,
# But we will use these patches along in case anything else goes wrong.
#
auto-team: false
bossbar-anti-flicker: false
bossbar-patch: true
chunk-border-fix: true
force-json-transform: true
item-cache: true
left-handed-handling: true
minimize-cooldown: true
no-delay-shield-blocking: false
prevent-collision: false
replace-pistons: false
replacement-piston-id: 0
shield-blocking: true
show-shield-when-sword-in-hand: true
simulate-pt: true
suppress-metadata-errors: true
use-new-deathmessages: true
use-new-effect-indicator: true
#
# World-Name translator configuration goes here,
#
# This is where we can specify the source's origin name and have it translated as the one we want,
# This may conflict with other world names that use similar friendly names but usually shouldn't happen on purpose.
#
map-1_16-world-names:
  abydos: sgjourney:abydos
  abyss: aoa3:abyss
  atlantis: atlantis:atlantis
  aether: aether:aether
  apalachia: divinerpg:apalachia
  apollo_moon: apollo:moon
  arcana: divinerpg:arcana
  astra_earthorbit: ad_astra:earth_orbit
  astra_glacio: ad_astra:glacio
  astra_glacioorbit: ad_astra:glacio_orbit
  astra_mars: ad_astra:mars
  astra_marsorbit: ad_astra:mars_orbit
  astra_mercury: ad_astra:mercury
  astra_mercuryorbit: ad_astra:mercury_orbit
  astra_moon: ad_astra:moon
  astra_moonorbit: ad_astra:moon_orbit
  astra_venus: ad_astra:venus
  astra_venusorbit: ad_astra:venusorbit
  backrooms: backrooms:level_0
  barathos: aoa3:barathos
  beyond_mercury: beyond_earth:mercury
  beyond_moon: beyond_earth:moon
  blended_world: world_blender:world_blender
  boil: jitl:boil
  bowsers_kingdom: super_block_world:bowsers_kingdom
  bright_overworld: daylightdimension:daylight_dimension
  bsr: bsr:bsr
  bsr_orbit: bsr:overworld_orbit
  bumblezone: the_bumblezone:the_bumblezone
  candyland: aoa3:candyland
  candy_world: betterswords:candy_dimension
  cave_world: mining_dims:caving_dim
  ceilands: ceilands:the_ceilands
  celeve: aoa3:celeve
  chulak: sgjourney:chulak
  cloudia: jitl:cloudia
  corba: jitl:corba
  creeponia: aoa3:creeponia
  crystevia: aoa3:crystevia
  crystal_world: palpexs_live:crystaldimsnion
  damnation: liroth:damnation
  dark_caverns: dark_caverns:dark_caverns
  dark_dungeon: dimdoors:dungeon_pockets
  dark_nether: better_nether_update:darkdimension
  dark_ocean: agape:europa_ocean
  deeplands: aoa3:deeplands
  deep_dark: paradisemod:deep_dark
  depths: jitl:depths
  devastated_plains: liroth:devastated_plains
  dustopia: aoa3:dustopia
  earth_orbit: beyond_earth:earth_orbit
  eden: divinerpg:eden
  eggcellent: the_eggcellent_mod:eggcellent_dimension
  ele_land: eleworld:eleland
  elysium: paradisemod:elysium
  emprus: the_emprus_max:emprus
  end: minecraft:the_end
  euca: jitl:euca
  europa: agape:europa_surface
  everbright: blue_skies:everbright
  everdawn: blue_skies:everdawn
  exotel: better_minecraft:exotel
  fishing_dimension: lobby:fishing_dimension
  flying_death: palpexs_live:flyingdeath
  forgotten_forest: forgotten_forest:forgotten_forest
  fraiya: lint:fraiya
  frozen: jitl:frozen
  galactic_moon: galacticraft:moon
  gaming_dimension: lobby:gaming_dimension
  ganymede: agape:ganymede
  glacio: beyond_earth:glacio
  glacio_orbit: beyond_earth:glacio_orbit
  glar_lands: glarlands:glarlands
  greckon: aoa3:greckon
  haven: aoa3:haven
  heaven: heaven:heaven
  heaven_2: heaven:sky
  herobrines_home: utopiacraft:herobrine_dimension
  hunting_world: mining_dims:hunting_dim
  iceika: divinerpg:iceika
  io: agape:io
  iromine: aoa3:iromine
  isle_of_dregs: jerrysmod:isle_of_dregs
  jalsphire_plains: liroth:jalsphire_plains
  jantiros_escape: liroth:jantiros_escape_dimension
  lane: revsdimensionmod:lane_dimension
  lantea: sgjourney:lantea
  lborean: aoa3:lborean
  lelyetia: aoa3:lelyetia
  limbo: dimdoors:limbo
  liroth: liroth:liroth_dimension
  lobby_dimension: lobby:lobby_dimension
  lost_city: lostcities:lostcity
  lost_paradise: paradise_lost:paradise_lost
  lunalus: aoa3:lunalus
  magnificent_lands: realmofmagnis:magnificent_lands
  mars: beyond_earth:mars
  mars_orbit: beyond_earth:mars_orbit
  meatopia: pork:meatopia
  mechanical: mechanical_mobs:god_dimension
  mechanical_forest: mechanical_mobs:mechanical_forest
  mechanical_slimes: mechanical_mobs:slime_dimension
  mechanical_world: mechanical_mobs:mechanical_world
  mercury: agape:mercury
  mercury_orbit: beyond_earth:mercury_orbit
  midnight: forgotten_forest:midnight
  mining_dimension: mining_dimension:mining
  mining_dimension_2: lobby:mining_dimension
  mining_end: mining_dimention:endminingdimension
  mining_horizon: minershorizon:miners_horizon
  mining_nether_world: mining_dims:nethering_dim
  mining_world: mining_dims:mining_dim
  molsh: mushroommill:molsh
  moon: agape:moon_surface
  moon_orbit: beyond_earth:moon_orbit
  mortum: divinerpg:mortum
  mushroom_kingdom: super_block_world:mushroom_kingdom
  mushy: mushroommill:mushy
  mutt: mushroommill:mutt
  mysterium: aoa3:mysterium
  mystic: oretacular:mystic_dimension
  nectere: hotm:nectere
  nether: minecraft:the_nether
  niccdsf: aywen_binggings_:niccdsf
  nowhere: aoa3:nowhere
  orbit: agape:overworld_orbit
  ore_land: eleworld:oreland
  origin: dimensional_expansion:origin
  overgrown: overgrowncities:overgrowth
  overworld: minecraft:overworld
  overworld_core: paradisemod:overworld_core
  paridise_islands: moron_mobs:paridise_islands
  popcorn_world: betterswords:popcorn_dimension
  purple_land: purple_land:purple_dimension
  precasia: aoa3:precasia
  prehistoric: eymbra:prehistoric
  radioactive: lukerosmod:radioactive_dimension
  red_planet: agape:red_planet
  runandor: aoa3:runandor
  scale_vacuum: scalevacuum:scale_vacuum
  sculk_depths: sculk_depths:sculk_depthsdim
  shyrelands: aoa3:shyrelands
  simple_void: simplevoidworld:simplevoidworld
  sky_lands: revsdimensionmod:sky_lands_dimenson
  space: astromine:earth_space
  spiderian: oretactular:spiderian_dimension
  starship: agape:starship_1
  sweet_and_savory: betterswords:sweet_and_savory_dimension
  terrania: jitl:terrania
  the_abyss: moron_mobs:abyss
  the_dungeon: dimdungeons:dungeon_dimension
  the_forest: liminals:the_forest
  the_hallow: thehallow:spooky
  the_mines: liminals:the_mines
  the_laboratory: createlab:laboratory
  the_parallax: nitramod:the_parallax
  the_private_room: dimdoors:personal_pockets
  the_public_room: dimdoors:public_pockets
  titan: agape:titan
  tropics: tropicraft:tropics
  twilight_forest: twilightforest:twilight_forest
  under_void: divine_faith:undervoid
  utopia: utopiacraft:utopiadimension
  venus: beyond_earth:venus
  venus_orbit: beyond_earth:venus_orbit
  vethea: divinerpg:vethea
  wildwood: divinerpg:wildwood
  void_dimension: lobby:void_dimension
  vox_ponds: aoa3:vox_ponds
