#
# Modifies the recipe book system to make it better,
# A portion of settings are disabled such as "unlockAll" to avoid causing problems.
#
darkMode = false
enableBook = true
enablePinning = true
keepCentered = true
settingsButton = false

[newRecipes]
enableBounce = true
unlockAll = false

[instantCraft]
showButton = false

[alternativeRecipes]
noGrouped = true
onHover = true

[scrolling]
enableScrolling = true
scrollAround = false
