#
# Dynamic FPS configuration goes here,
#
# This allows the client to reduce FPS when unfocused and vice versa,
# but also makes the in-game audio quiet + runs the garbage collector combined when unfocused.
#
hiddenVolumeMultiplier = 0.0
reduceFPSWhenUnfocused = true
restoreFPSWhenHovered = true
runGCOnUnfocus = true
unfocusedFPS = 1
unfocusedVolumeMultiplier = 0.12
