#
# Lithium configuration goes here,
#
# This is used to turn off Lithium-related mixins that may cause incompatibilities with third-party mods when paired with this mod,
# this configuration should not be modified unless said mod has been patched or there is another mixin that has to be disabled.
#
# Full lithium mixin documentation can be discovered here:
# https://github.com/CaffeineMC/lithium-fabric/blob/develop/dev/lithium-mixin-config.md
#
mixin.ai.task.memory_change_counting=false
mixin.alloc.entity_tracker=false
mixin.block.hopper=false
mixin.collections.chunk_tickets=false
mixin.collections.fluid_submersion=false
mixin.entity.collisions=false
mixin.entity.collisions.fluid=false
mixin.entity.collisions.intersection=false
mixin.entity.collisions.movement=false
mixin.entity.collisions.unpushable_cramming=false
mixin.entity.fast_powder_snow_check=false
mixin.experimental=false
mixin.experimental.entity.block_caching.fluid_pushing=false
mixin.experimental.entity.block_caching.suffocation=false
mixin.experimental.entity.item_entity_merging=false
mixin.minimal_nonvanilla.collisions.empty_space=false
mixin.minimal_nonvanilla.world.block_entity_ticking.support_cache=false
mixin.minimal_nonvanilla.world.expiring_chunk_tickets=false
mixin.util.world_border_listener=false
mixin.world.block_entity_ticking.sleeping=false
mixin.world.block_entity_ticking.sleeping.brewing_stand=false
mixin.world.block_entity_ticking.sleeping.campfire=false
mixin.world.block_entity_ticking.sleeping.campfire.lit=false
mixin.world.block_entity_ticking.sleeping.campfire.unlit=false
mixin.world.block_entity_ticking.sleeping.furnace=false
mixin.world.block_entity_ticking.sleeping.hopper=false
mixin.world.block_entity_ticking.sleeping.shulker_box=false
mixin.world.block_entity_ticking.world_border=false
mixin.world.game_events.dispatch=false
mixin.world.temperature_cache=false
mixin.world.tick_scheduler=false
mixin.gen.cached_generator_settings=false
