#
# Old Potions configuration goes here,
#
# This restores the glinting effect back to the potions,
# and also the original colors back to them before they were cut in vanilla.
#
enable_glint = true
old_colors = true
