#
# Remove Reloading Screen configuration goes here,
#
# This will tell Remove Reloading Screen to show the progress bar,
# whilst taking care of everything else without including distractions.
#
animationSpeed = 250.0
blockOverlay = false
doubleLoad = "LOAD"
earlyPackStatusSend = true
enableScissor = true
hideOverlays = "RELOADING"
miniRender = true
reInitScreen = true
reloadText = ""
removeOverlayAtEnd = true
resetResources = true
rgbProgress = false
type = "PROGRESS"
