#
# Remove Reloading Screen configuration goes here,
#
# This will tell Remove Reloading Screen to show the progress bar,
# whilst taking care of everything else without including distractions.
#
animationSpeed = 250.0
aprilFool = "DISABLED"
earlyPackStatusSend = true
forceClose = false
hideType = "RELOADING"
miniRender = true
reInitScreen = true
reloadText = ""
resetResources = true
rgbProgress = false
type = "PROGRESS"
