#
# Remove Reloading Screen configuration goes here,
#
# This will tell Remove Reloading Screen to show the progress bar,
# whilst taking care of everything else without including distractions.
#
animationSpeed = 1500.0
hideType = "RELOADING"
reInitScreen = true
reloadText = ""
resetResources = true
rgbProgress = false
showIn = "ALL"
type = "PROGRESS"
