#
# Sodium Extras configuration goes here,
#
# This is used to turn off Sodium Extras-related mixins that may cause incompatibilities with third-party mods when paired with this mod,
# this configuration should not be modified unless said mod has been patched or there is another mixin that has to be disabled.
#
# Full Sodium Extras mixin documentation can be discovered here:
# https://github.com/FlashyReese/sodium-extra-fabric/blob/1.21/dev/common/src/main/java/me/flashyreese/mods/sodiumextra/client/SodiumExtraClientMod.java
#
mixin.animation=false
mixin.instant_sneak=false
mixin.light_updates=false
mixin.prevent_shaders=false
mixin.profiler=false
mixin.reduce_resolution_on_mac=false
mixin.optimizations.draw_helpers=false
mixin.biome_colors=false
mixin.sky=false
mixin.sky_colors=false
