#
# Title Fixer configuration goes here,
#
# This modifies the titles and scoreboards when displayed on screen,
# These should only be modified in case something is in error.
#
preferredSubtitleScale = 2.0
preferredTitleScale = 4.0
scoreboardFadeSpeed = 0
scoreboardHideMinAlpha = 0
scoreboardMode = "OVERLAY"
titleAlwaysFitsScreen = true
titleMarginLeft = 8
titleMarginRight = 8
