[global]
	hideOverlays = "RELOADING"
	blockOverlay = false
	miniRender = true
	enableScissor = true

[splash]
	type = "PROGRESS"
	rgbProgress = false
	reloadText = ""
	animationSpeed = 250.0

[interpolation]
	interpolateProgress = false
	interpolateAtEnd = false
	ease = "INOUTQUINT"
	easingArg = nan

[other]
	resetResources = true
	reInitScreen = true
	earlyPackStatusSend = true
	doubleLoad = "LOAD"

[platform]
	skipForgeOverlay = true
