#
# Sodium configuration goes here,
#
# This is used to turn off Sodium-related mixins that may cause incompatibilities with third-party mods when paired with this mod,
# this configuration should not be modified unless said mod has been patched or there is another mixin that has to be disabled.
#
# Full Sodium mixin documentation can be discovered here:
# https://github.com/CaffeineMC/sodium/blob/dev/common/src/main/java/net/caffeinemc/mods/sodium/client/data/config/MixinConfig.java
#
mixin.debug.checks=false
mixin.features.render.world.sky=false
mixin.features.shader=false
mixin.features.shader.uniform=false
