#
# Geyser configuration goes here,
#
# This is where we can set up the Geyser port and other information for bedrock players,
# such as sending out the correct MOTD and other required details, Other information can be found here:
#
# https://wiki.geysermc.org/geyser/understanding-the-config
#

#
# Bedrock connectivity configuration goes here,
#
# This is currently WIP - The port has to be manually changed when opening LAN worlds-
# -with an customized port number - the default 25565 port should be no issue if left unchanged.
#
bedrock:
  address: 0.0.0.0
  port: 25565
  clone-remote-port: true
  motd1: "§cMCWine"
  motd2: "§9Another Minecraft Server"
  server-name: "MCWine"
  compression-level: 6
  enable-proxy-protocol: false
#
# Java connectivity configuration goes here.
#
remote:
  address: 0.0.0.0
  port: 25565
  auth-type: floodgate
  allow-password-authentication: false
  use-proxy-protocol: false
  proxy-protocol-whitelisted-ips: [ "127.0.0.1" ]
  forward-hostname: true
#
# Floodgate-related and other connectivity configuration goes here.
#
enable-proxy-connections: false
floodgate-key-file: key.pem
forward-player-ping: true
legacy-ping-passthrough: false
log-player-ip-addresses: false
mtu: 1400
passthrough-motd: true
passthrough-player-counts: true
passthrough-protocol-name: false
pending-authentication-timeout: 360
ping-passthrough-interval: 5
saved-user-logins: []
use-direct-connection: true
#
# In-Game bedrock configuration goes here,
#
# Mostly everything in this area can be completely modified without issues,
# Although a bit of thoughts should be taken into before changing any of these.
#
above-bedrock-nether-building: true
add-non-bedrock-items: true
allow-custom-skulls: true
allow-third-party-capes: false
allow-third-party-ears: false
always-quick-change-armor: false
cache-images: 0
command-suggestions: false
custom-skull-render-distance: 8
disable-bedrock-scaffolding: true
emote-offhand-workaround: "disabled"
force-resource-packs: false
max-players: 8
max-visible-custom-skills: 128
scoreboard-packet-threshold: 60
show-cooldown: title
show-coordinates: true
xbox-achievements-enabled: false
#
# Debugging configuration goes here.
#
config-version: 4
debug-mode: false
default-locale: en_us
notify-on-new-bedrock-update: false
metrics:
  enabled: false
  uuid: generateduuid
