#
# ViaBackwards patches for older versions go here,
#
# This will attempt to patch more details for older versions that do not match server's version,
# and also enable the player to figure out what the translated mobs are and whatnot.
#
always-show-original-mob-name: true
add-custom-enchants-into-lore: true
add-teamcolor-to-prefix: false
chat-types-1_19_1:
  "chat.type.announcement": "[%s] %s"
  "chat.type.emote": "* %s %s"
  "chat.type.team.sent": "-> %s <%s> %s"
  "chat.type.team.text": "%s <%s> %s"
  "chat.type.text": "<%s> %s"
  "commands.message.display.incoming": "%s whispers to you: %s"
  "commands.message.display.outgoing": "You whisper to %s: %s"
fix-1_13-face-player: true
fix-formatted-inventory-titles: true
handle-pings-as-inv-acknowledgements: true
