#
# ViaBackwards patches for older versions go here,
#
# This will attempt to patch more details for older versions that do not match server's version,
# and also enable the player to figure out what the translated mobs are and whatnot,
#
# References to every config detail can be discovered here:
# https://github.com/ViaVersion/ViaBackwards/blob/master/common/src/main/resources/assets/viabackwards/config.yml
#
always-show-original-mob-name: true
add-custom-enchants-into-lore: true
add-teamcolor-to-prefix: false
bedrock-at-y-0: false
fix-1_13-face-player: true
fix-formatted-inventory-titles: true
handle-pings-as-inv-acknowledgements: true
sculk-shriekers-to-crying-obsidian: true
suppress-emulation-warnings: true
